name: nano
description: An application architecture pattern than a framework for Flutter utilizing a unidirectional data flow.
version: 0.1.0
homepage: https://github.com/purplecandy/nano

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  rxdart: "^0.24.1"
  meta: "^1.1.8"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: