name: nano
description: Nano makes it easier to build and maintain complex Flutter apps.
version: 0.3.1
homepage: https://github.com/purplecandy/nano

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  rxdart: ^0.27.2
  meta: ^1.7.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: