name: nano
description: An easy to use modular state management library
version: 0.0.1
homepage: https://github.com/purplecandy/nano

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  rxdart: "^0.24.1"
  meta: "^1.1.8"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter: