name: contacts
description: A contacts module

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cloud_firestore:
  auth:
    path: ../auth/
  nano:
    path: ../../../../
  flutter:
    sdk: flutter